version: '3.1'

services:

  database:
    image: postgres
    environment:
      - POSTGRES_DB=nest_api
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
   